name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 6044:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          cd IQWorld
          composer install --prefer-dist --no-interaction --no-progress
      - name: Create database
        run: |
          mysql --host 127.0.0.1 --port 6044 -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS db_IQWorld;'
      - name: Migrate Datas
        run: |
          cd IQWorld
          php artisan migrate
      - name: Run tests
        run: |
          cd IQWorld 
          php artisan test
