name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd sous-repertoire
          composer install --prefer-dist --no-interaction --no-progress
              
      - name: Run tests
        run: php artisan test
